export const FETCH_CHEMICAL_RECORD_REQUEST = 'FETCH_CHEMICAL_RECORD_REQUEST';
export const FETCH_CHEMICAL_RECORD_SUCCESS = 'FETCH_CHEMICAL_RECORD_SUCCESS';
export const FETCH_CHEMICAL_RECORD_ERROR = 'FETCH_CHEMICAL_RECORD_ERROR';
